services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: tll
      POSTGRES_PASSWORD: tll_pass
      POSTGRES_DB: tll
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: